# Generated by Django 5.2.8 on 2025-12-10 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "tour",
                    models.CharField(
                        choices=[("ATP", "ATP"), ("WTA", "WTA"), ("ITF", "ITF")],
                        max_length=10,
                    ),
                ),
                ("external_api_id", models.CharField(max_length=100, unique=True)),
                ("ranking", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "players",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FavouritePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_players",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourited_by",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "db_table": "favourite_players",
                "ordering": ["-added_at"],
                "unique_together": {("user", "player")},
            },
        ),
    ]
